### ISSUE TITLE
Feature Request: Create and remove locks within a jenkinsfile

### ISSUE THREAD

**Issue by wagoodman** [jenkinsci/lockable-resources-plugin#104]
It would be ideal to create an arbitrary lock and use it for a period of time, and optionally delete it. Having a self-creating and self-deleting lock would give the ability to lock resources which definitions change frequently but is already tracked in code. 

Example usage could look like:
```
def app_name = 'my-awesome-app'
// ...snip...
lock(resource: "${app_name}:staging", ephemeral: true) {
   // ... lock created and acquired... deploy this app to the staging environment
}
// by this point the lock is released and destroyed
```

where the lock name `my-awesome-app:staging` would be created and reserved by the pipeline, and once the lock is out of scope it is deleted. Maybe even allow someone the ability to control create and delete actions: `lock(resource: ..., create: true, delete: false) { ... }`

I realize this is very similar to #103 but didn't want to hijack that conversation for something that has clearly different features (but also a lot of overlap).

**Comment by shantur** [comment]
I have implemented this in #124

**Comment by clonejo** [comment]
So this issue can be closed?

**Comment by TobiX** [comment]
Will be in the next release, see #138.

**Comment by shantur** [comment]
@TobiX : When is the next release, I am waiting for this change.
