### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property: Artifactory for class: Script1

### ISSUE THREAD

**Issue by Mohitg06** [jenkinsci/lockable-resources-plugin#111]
I keep getting this error groovy.lang.MissingPropertyException: No such property: Artifactory for class: Script1
 def server= Artifactory.server ('$SERVER_NAME')
I am running Groovy script inside Jenkins. as  Execute System Groovy script.
Artifactory Plugin:  2.16.2
Groovy version: 2.5.2, I have played with few downgraded versions, I still get the same error.

Can I know what am I missing?

**Comment by thanh3d** [comment]
same to me, after update git plugin.

**Comment by TobiX** [comment]
This is not the artifactory plugin.
