### ISSUE TITLE
Lock with only label not matching a resource silently does not lock anything

### ISSUE THREAD

**Issue by reftel** [jenkinsci/lockable-resources-plugin#114]
Given the following pipeline, and no defined resources, the critical section is allowed to run in parallel:

```
lock(label:"foo") {
  echo "Critical"
}
```

If a resource name had been used instead of a label, the resource would have been created and locked. I would have expected `lock` to either auto-create the resource or error out due to the resource being missing.

**Comment by EbenZhang** [comment]
👍 auto-create the resource

**Comment by jimklimov** [comment]
I'd go for blocking the build in the queue, as long as you required one or more resource instances and could not get any, whatever the reason. It would be clearer to administer and fix in an installation.

Blind auto-creation may be a problem with e.g. typos and/or strings passed from outside (build args, etc.); an explicit option flag "Here I want auto-creations allowed" makes sense however. Maybe tied into Jenkins security (add/use an assignable permission for the user who executes the build to create resources).

**Comment by TobiX** [comment]
Trying to lock on non-existing labels now fails the build, see #108.
