### ISSUE TITLE
Provide option to not unlock resource when job is finished

### ISSUE THREAD

**Issue by bkhouri** [jenkinsci/lockable-resources-plugin#120]
We have a need where we do not want to unlocked the locked resource so we can troubleshoot test failures.

We currently use declarative pipeline and lock the resource in the `options` "steps"

e.g.:
```
pipeline {
    options {
        lock(...)
    }
}
```

Can we have an option `doNotUnlockResource` or something similar, that will leave the resource locked when we exit the `lock` block?

e.g.:
```
pipeline {
    options {
        lock(...)
    }
    stages {
        stage("") {
            // do stuff
        }
        // more stages
        post {
            always {
                doNotUnlockResource
            }
        }
    }
}
```

**Comment by jimklimov** [comment]
Not a duplicate, but maybe a synergetic idea with #142.

**Comment by mPokornyETM** [comment]
Duplicate to #253
