### ISSUE TITLE
Lock keeps executor when run in declarative pipeline in SCM

### ISSUE THREAD

**Issue by rob-spoor** [jenkinsci/lockable-resources-plugin#135]
We have some JenkinsFiles in SCM that all contain declarative pipelines. These all have the same basic setup:

	pipeline {
		agent any

		options {
			lock(resource: "lock")
		}

		...
	}

All build of these jobs are correctly blocked. However, the locking occurs within an executor. The reason is probably that the executor is already needed to check out the pipeline itself. The result is that all slots are quickly filled by builds that are waiting on the lock.

Is it possible to change this plugin to "unclaim" the executor so the build goes back into the pool, and the executor can be used for other builds?

**Comment by skorhone** [comment]
I don't think there is anything that could be done in this plugin. You should be defaulting to agent none and allocate node (agent) only when you need it.

Input step behaves similarly when ran with agent any

**Comment by TobiX** [comment]
I'm with @skorhone here. AFAIK you can nest steps in declarative, so you can lock an outer step with `agent none` and allocate the node only in the inner step.
