### ISSUE TITLE
Feature request : additional text field support

### ISSUE THREAD

**Issue by leon-gh** [jenkinsci/lockable-resources-plugin#140]
Sometimes resources are used by people, other times they are used by automated testing tools, CICD, etc. It would be nice to have an extra text field that would allow adding additional info, a description, about why the resource is being used. It should act as an optional field when locking a resource.

For instance, a person could say: need this resource from date1 to date2
Automation tool could say: automation, running <test-id>
etc.

Without it, we need to keep a track of this in a separate database and/or find people who reserved resources, ask them whether they still need them, etc.

**Comment by jimklimov** [comment]
Revived PR merged as part of #273 (or some nearby) I think.
