### ISSUE TITLE
No documentation for extra usage

### ISSUE THREAD

**Issue by jwillemsen** [jenkinsci/lockable-resources-plugin#176]
We found that extra can be used to implement an optional lockable step which is based on a variable set or not. We found usage of extra in the changes below, the extra functionality should be documented

Combined with pipeline parameters as explained on https://jenkins.io/blog/2017/10/02/pipeline-templates-with-shared-libraries/ we do now

```
lock(
extra: (pipelineParams.containsKey('buildresource') ? [[resource: pipelineParams.buildresource]] : [])
)
```

https://github.com/SUSE-Cloud/automation/pull/3746/files
https://github.com/stefannica/automation/blob/df85611aa9d3d065f26779c1f0050972a66d51d2/jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile

**Comment by TobiX** [comment]
It is documented in the Pipeline snippet generator and the [pipeline step reference](https://jenkins.io/doc/pipeline/steps/lockable-resources/#lock-lock-shared-resource)

**Comment by TobiX** [comment]
Since #169 stumbled over the same problem, these seem to be hard to find...

**Comment by jwillemsen** [comment]
Yes, that docu is hard to find, maybe add a link to it from the readme.md of this project and https://wiki.jenkins.io/display/JENKINS/Lockable+Resources+Plugin

**Comment by jwillemsen** [comment]
We have all our groovy scripts in git, all code is outside of Jenkins, so the snippet generator is not used much, when we started with declarative pipelines we used it but at that point it was very very limited

**Comment by jwillemsen** [comment]
Fixed by https://github.com/jenkinsci/lockable-resources-plugin/pull/177
