### ISSUE TITLE
Unable to use skipIfLocked

### ISSUE THREAD

**Issue by mosaic-nick** [jenkinsci/lockable-resources-plugin#197]
Hi,

When attempting to do:

lock(resource: 'lock-test-resource', skipIfLocked: true) {
   ...
}

I get the following:

16:07:20  WARNING: Unknown parameter(s) found for class type 'org.jenkins.plugins.lockableresources.LockStep': skipIfLocked
16:07:20  Trying to acquire lock on [lock-test-resource]
16:07:20  Found 0 available resource(s). Waiting for correct amount: 1.
16:07:20  [lock-test-resource] is locked by Utilities » lock-1 #6, waiting...

i.e. it is not skipping if locked :(

I also note that https://jenkins.io/doc/pipeline/steps/lockable-resources/ does **not** mention the skipIfLocked parameter.

I'm using Jenkins 2.204.5 with version 2.7 of the lockable resources plugin (no update available).

Can anyone shed any light on why this isn't working? Am I doing something stupid?

Thanks,
Nick

**Comment by TobiX** [comment]
There hasn't been a release after the feature was added - If you feel adventurous, you can try a build from master: https://ci.jenkins.io/job/Plugins/job/lockable-resources-plugin/job/master/

**Comment by mosaic-nick** [comment]
Ah, that explains it. But it's included in the plugin docs at https://plugins.jenkins.io/lockable-resources/, where it probably should not be. Not sure I feel brave enough to go with master - do you know when you're planning your next release? Thanks

**Comment by TobiX** [comment]
Interesting, I thought the plugin site shows the documentation of the latest release... I see if I get around publishing a release this weekend

**Comment by mosaic-nick** [comment]
That'd be great - looking forward to trying it out! Thanks

**Comment by TobiX** [comment]
@mosaic-nick I released a new version yesterday, please try with that version.
