### ISSUE TITLE
Lock All resources by setting quantity to 0 is not documented

### ISSUE THREAD

**Issue by akomakom** [jenkinsci/lockable-resources-plugin#198]
Experimentally I discovered that setting quantity to zero results in locking all resources with the given label.  In other words, `quantity: 0` is the same as `quantity: 100` if there are 100 resources.
 
```groovy
lock(label: 'my-label', quantity: 0) {
}
```

This is either an undocumented feature or an unintended result.  
- If it's undocumented, I'm happy to supply a PR for the readme and jelly.  
- If it's not to be relied upon, please let me know.

I personally find this to be a useful feature.

**Comment by TobiX** [comment]
It's the same as not specifying quantity at all, and I agree, it's pretty underdocumented. It's missing at least in the context-senstive help:

- https://github.com/jenkinsci/lockable-resources-plugin/blob/488de1515354b77b1900d10165475acf28773e51/src/main/resources/org/jenkins/plugins/lockableresources/LockStep/help-quantity.html
- https://github.com/jenkinsci/lockable-resources-plugin/blob/488de1515354b77b1900d10165475acf28773e51/src/main/resources/org/jenkins/plugins/lockableresources/LockStepResource/help-quantity.html

You can see that the default is indeed 0:
https://github.com/jenkinsci/lockable-resources-plugin/blob/21cb4315c5abe032f4aa4f65e7e76d5439d3c272/src/main/java/org/jenkins/plugins/lockableresources/LockStep.java#L30
and
https://github.com/jenkinsci/lockable-resources-plugin/blob/21cb4315c5abe032f4aa4f65e7e76d5439d3c272/src/main/java/org/jenkins/plugins/lockableresources/LockStepResource.java#L26

It seems to be documented for FreeStyle jobs (a bit - confusingly it's called resourceNumber there):
https://github.com/jenkinsci/lockable-resources-plugin/blob/21cb4315c5abe032f4aa4f65e7e76d5439d3c272/src/main/resources/org/jenkins/plugins/lockableresources/RequiredResourcesProperty/help-resourceNumber.html

The code in `LockableResourcesManager` seems to make sure that you always get "all" resources when trying to lock with quantity 0.
