### ISSUE TITLE
Feature request: configurable priorities

### ISSUE THREAD

**Issue by mhier** [jenkinsci/lockable-resources-plugin#201]
Please add a parameter "priority" to the lock() function, which takes an integer number that defines the order in which concurrent jobs waiting for the same resource are served. The job with the highest number would get the resource first. If the priority is equal, the current precedence (first comes first, unless inversePrecedence is true) would be applied.

**Comment by TobiX** [comment]
This feature was removed in version 1.7 of this plugin (see https://github.com/jenkinsci/lockable-resources-plugin/commit/a07a64244e3ee2b65a67d5111a6e8aa90c2b3249), long before I took over maintainership. The commit suggests this could be done with external plugins, but I currently see no extension point to facilitate this...

**Comment by mPokornyETM** [comment]
> This feature was removed in version 1.7 of this plugin (see [a07a642](https://github.com/jenkinsci/lockable-resources-plugin/commit/a07a64244e3ee2b65a67d5111a6e8aa90c2b3249)), long before I took over maintainership. The commit suggests this could be done with external plugins, but I currently see no extension point to facilitate this...

In that case shall be reverted. I will like this feature too.

**Comment by mPokornyETM** [comment]
See also #223

**Comment by mPokornyETM** [comment]
See also #201

**Comment by mPokornyETM** [comment]
@rjarry had you any idea why it was removed?

**Comment by rjarry** [comment]
This was a long time ago. I think it was to allow using lockable-resources with https://plugins.jenkins.io/PrioritySorter/

**Comment by lppedd** [comment]
Hey everyone! I'm interesting in prioritizing production branches over PRs. This seems to do it, any news?

**Comment by mPokornyETM** [comment]
@lppedd  Currently not. Let me see what will be possible. Or do you want to participate. Any help are welcome.

**Comment by lppedd** [comment]
@mPokornyETM it's just strange this was removed in the commit mentioned above.  
The alternative plugins do not do the same at all.

**Comment by mPokornyETM** [comment]
> @mPokornyETM it's just strange this was removed in the commit mentioned above. The alternative plugins do not do the same at all.

even better, It shall be easy to revert the commit. I hope.
