### ISSUE TITLE
Feature Request: Resource Pool with quantity 

### ISSUE THREAD

**Issue by nrayapati** [jenkinsci/lockable-resources-plugin#208]
Looks like currently we can only define a single resource with same name, it would nice if this plugin support the pool of resources with quantity with same name. 

Like: 
Printers - 10  - Instead of defining 10 resources with unique name each it would be nice to have a one resource with 10 available quantity.

**Comment by TobiX** [comment]
This is already tracked as #128

**Comment by nrayapati** [comment]
Thank you @TobiX for the direction.
