### ISSUE TITLE
On Safari the lockable-resources/ page has trouble being displayed.

### ISSUE THREAD

**Issue by cedriclecoz** [jenkinsci/lockable-resources-plugin#210]
Hi,

On Safari the lockable-resources/ page has trouble being displayed to looks like the header take 95% of the screen.
No problem on Firefox.
I am on Jenkins 2.235.1 and Lockable Resources Plugin 2.8

bellow a screenshot

<img width="1624" alt="Screenshot 2020-07-12 at 20 49 50" src="https://user-images.githubusercontent.com/12274523/87255319-baadd080-c481-11ea-9216-a7fe3853fe1f.png">

https://ibb.co/Dp938LR

C.

**Comment by TobiX** [comment]
I don't have a system to test this on, unfortunately. Maybe that was a side-effect of the broken HTML? Can you test with version 2.10?

**Comment by clonejo** [comment]
A colleague ran into this a while ago on her Mac, i hope i can remember to ask her about this again.

IIRC it did fix itself when the window is resized.

**Comment by cedriclecoz** [comment]
Apologies for the delay, way too long jobs running thought the past WEs... 
Issue is fixed thanks!
Tested on core 2.249.2, plugin 2.10
