### ISSUE TITLE
Declarative pipeline validation error when using label

### ISSUE THREAD

**Issue by t-gebauer** [jenkinsci/lockable-resources-plugin#211]
Using the `lock` step in a declarative pipeline with label parameter does not validate. Apparently the 'resource' parameter is seen as required.

```
Errors encountered validating Jenkinsfile:
WorkflowScript: 232: Missing required parameter: "resource".
                   lock(label: 'Printer', quantity: 1, variable: 'LOCKABLE_RESOURCE') {
                   ^
```

**Comment by TobiX** [comment]
This is a restriction of the declarative syntax validator. See https://issues.jenkins-ci.org/browse/JENKINS-43002 for details...
