### ISSUE TITLE
Lockable resources - HTTP ERROR 403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by Lieth** [jenkinsci/lockable-resources-plugin#218]
When I try to lock a lockable resource by using the GUI I get the above error about a valid crumb. When I searched the history of errors I found an earlier error that was already resolved but it either wasn't solved compleatly or has reappeared. We are running version 2.259 of Jenkins. It works fine when triggered in pipelines.

Below is the error notification that is shown after trying to lock a resource.

URI:	/lockable-resources/reserve
STATUS:	403
MESSAGE:	No valid crumb was included in the request
SERVLET:	Stapler

**Comment by TobiX** [comment]
Are you using version 2.9? This was an oversight in the security fix, which should have been fixed in 2.10. (See #217)

**Comment by Lieth** [comment]
Not sure what you mean. Today we got an update request for jenkins which states version 2.260 (New version of Jenkins (2.260) is available for download (changelog).)

At the moment we have version 2.259, or is there some other version you want me to find out?

**Comment by Lieth** [comment]
Ah now I see, the plugin for lockable resource, will try to update it and report back once its done
