### ISSUE TITLE
Job DSL plugin issue

### ISSUE THREAD

**Issue by pingwhistle** [jenkinsci/lockable-resources-plugin#22]
When using the lockable-resources plugin with the Job DSL plugin, the generated snippet within config.xml appears to be incorrect:

```
        <org.jenkins.plugins.lockableresources.RequiredResourcesProperty>
            <resourceNames>lock-resource</resourceNames>
        </org.jenkins.plugins.lockableresources.RequiredResourcesProperty>
```

As expected, running the job(s) fails to lock the resource.

If I edit the generated job manually and configure the lockable resource, its replaced with this:

```
      <org.jenkins.plugins.lockableresources.RequiredResourcesProperty plugin="lockable-resources@1.7">
        <resourceNames>lock-resource</resourceNames>
      </org.jenkins.plugins.lockableresources.RequiredResourcesProperty>
```

This works as expected, so I'm not sure if the issue lies with JobDSL or lockable-resources plugin.

Jenkins: 1.638
Java: 1.8
Lockable Resources: 1.7
Job DSL: 1.40

**Comment by jimklimov** [comment]
Given the age of the issue and that I've never seen this problem in practice, I am inclined to close it. Feel free to revive if it still happens with current releases.
