### ISSUE TITLE
[Question] How to lock a resource for an entire declarative pipeline?

### ISSUE THREAD

**Issue by myxal** [jenkinsci/lockable-resources-plugin#220]
The documentation mentions the `This build requires lockable resources` option for freestyle job, but for pipelines, only the lock step is mentioned (and the config option is not available), which only locks the resources for whatever steps are within its body. If this should allow for locking for the entire pipeline duration, I can't figure out where to put the `lock` step to achieve this:

```
pipeline{
  agent { ...}
  stages{
    stage (...){
    ...
    }
    stage (...){
    ...
    }
  }
  post {
    always {
    ...
    }
    successful{
    ...
    }
  }
}
```

Is there a way to lock resources for the entirety of pipeline duration, or at least all the stages + post scopes? I came across #164 and #185 which would ultimately be the best "generic" solution, but AFAICT, they're not merged and released.

I guess I could use `build` under `lock` in another, "wrapper" job, but having to do all that seems a bit silly.

**Comment by TobiX** [comment]
I'm personally not using declarative pipeline, but AFAIK you can use a "wrapper" stage with `agent none` around the rest of of your stages to have a lock for the whole pipeline run... Maybe ask your question in the https://www.jenkins.io/sigs/pipeline-authoring/ SIG? This sounds like something that should be possible...

**Comment by famod** [comment]
Just add `lock(...)` to `options`:
```
pipeline {
  options {
    lock(resource: 'foo')
  }
```

**Comment by myxal** [comment]
Thanks, this does indeed work. 👍
