### ISSUE TITLE
Provide a list of "waiting" job for lockable resources in the order they will be treated

### ISSUE THREAD

**Issue by ykoehler** [jenkinsci/lockable-resources-plugin#222]
It would be desirable to see which job is next for the locks once it gets released.

Likely in the page where the lockable are displayed:

https://jenkins-ion.arubanetworks.com/lockable-resources/

We can today see that a lock is used or not, but adding a "list of pending lock requests" would help the user understand their job is likely to get the lock.

**Comment by mPokornyETM** [comment]
Probably fixed by #452
