### ISSUE TITLE
Lockable priority strategy

### ISSUE THREAD

**Issue by ykoehler** [jenkinsci/lockable-resources-plugin#223]
At this time, the lockable resource provides the inversePrecedence which I think should be true by default, but such functionality, I believe is only per folder.  In a scenario where one uses the Jenkins branches source where each git branch/pr is a folder, a more elaborate strategy may be required to give precedence to branch such as release/*, hotfix/* before bugfix/*, feature/*, PR, etc.

There is already 2 plugin that can achieve such thing, PrioritySorter and Multi-branch PrioritySorter, but they only work for "starting" a job, once the job reaches a lock() statement, the strategy used gets lost.

As such, the lockable should integrate the functionality of PrioritySorter or honor the existing one.

**Comment by mPokornyETM** [comment]
This is very good idea. I like it. The same issue on our side. Whe we need to test hotfix it is more important than some feature branch test.
