### ISSUE TITLE
Add reserved timestamp field in locable resource list

### ISSUE THREAD

**Issue by primoz-p** [jenkinsci/lockable-resources-plugin#225]
Sometimes, it is good to know when a resource was reserved/locked.

For instance, if it was locked for a few hours or even days, it should be ok but after weeks/months you could probably unreserve it without any problems.

The timestamp value should be set automatically when a resource is reserved/locked and clear after resource unreserve or unlocked.

**Comment by primoz-p** [comment]
#226

**Comment by rnickle79** [comment]
I would be great if this timestamp was visible on the Lockage Resources page too.

**Comment by primoz-p** [comment]
> I would be great if this timestamp was visible on the Lockage Resources page too.

@rnickle79 , which page to you mean?

**Comment by rnickle79** [comment]
> > I would be great if this timestamp was visible on the Lockage Resources page too.
> 
> @rnickle79 , which page to you mean?

@primoz-p  http://<jenkins url>/lockable-resources/

**Comment by primoz-p** [comment]
> > > I would be great if this timestamp was visible on the Lockage Resources page too.
> > 
> > 
> > @rnickle79 , which page to you mean?
> 
> @primoz-p http://<jenkins url>/lockable-resources/

The timestamp is visible there.
![image](https://user-images.githubusercontent.com/68027674/107338746-31fd1e80-6abc-11eb-8943-5724317a9a52.png)

**Comment by jimklimov** [comment]
A variant of this was merged, thanks to everyone involved! :)
