### ISSUE TITLE
Support for locking for multiple resource groups

### ISSUE THREAD

**Issue by mridang** [jenkinsci/lockable-resources-plugin#23]
It seems that one Jenkins build can only get a resource lock on one resource group. I'd like to get a lock on multiple resource groups.

RASPBERRIES (label): RP_1, RP_2, RP_3
TABLES (label): GALAXY_1, GALAXY_2, GALAXY_3

My build has a place where I can specify that I'd like a lockable resoirce from `RASPBERRIES` but I cannot get a lock on one `RP_X` and one `GALAXY_X`

**Comment by TobiX** [comment]
This has been available for pipeline jobs for quite some time. I don't consider building the same for legacy jobs worthwhile. I would, however, consider merging a well-written & tested pull requests adding such a feature.
