### ISSUE TITLE
Return error when resource is already reserved or locked

### ISSUE THREAD

**Issue by primoz-p** [jenkinsci/lockable-resources-plugin#230]
Currently, when do you want to reserve already reserved (or locked or queued) resources, nothing happens. 
This "false" is simply ignored:
https://github.com/jenkinsci/lockable-resources-plugin/blob/094568f3dde3b2a4b0d263c8afa90bcc0cac7a57/src/main/java/org/jenkins/plugins/lockableresources/LockableResourcesManager.java#L601

I suggest returning an error when this happens.

**Comment by mPokornyETM** [comment]
It looks to be fixed 

https://github.com/jenkinsci/lockable-resources-plugin/blob/157231b038826857609ec0ea62e684dec5e0c159/src/main/java/org/jenkins/plugins/lockableresources/actions/LockableResourcesRootAction.java#L198
