### ISSUE TITLE
Lockable resources are only locked for jobs that use `lock()`?

### ISSUE THREAD

**Issue by raketenolli** [jenkinsci/lockable-resources-plugin#232]
I created a Jenkins job with a declarative pipeline that uses several resources, so at the start I lock them using

```groovy
pipeline {
  agent none
  options {
    lock(extra: [[resource: 'A'], [resource: 'B'], [resource: 'C']])
  }
  stages {
    stage('Part A') {
      agent { node { label: 'A' } }
      steps { ... }
    }
    etc.
  }
}
```

If I trigger a second instance of this job soon after the first one, the second will try to acquire locks, but can't, and hence will wait for the resources to become available again. This is the desired behavior.

If I create a job that does not try to lock the resource it wants to use, e.g. `C`,

```groovy
pipeline {
  agent none
  stages {
    stages('C') {
    agent { node { label 'C' } }
    steps { ... }
  }
}
```
(of course the job is more complex)

it will use resource `C` even though it should be locked by the job described at the top of the post (unless the first job is currently using that resource).

Is this a bug, the intended behavior or a limitation of the Jenkins technology, that the lockable-resources plugin can only lock resources for jobs using the plugin, but other jobs will be completely ignorant of resources being lockable or locked?

**Comment by TobiX** [comment]
This is an inherent limitation of all "tacked-on" lock primitives. Only actors "playing by the rules" participate in the locking.
