### ISSUE TITLE
Acquiring of empty resource if timeout is expired

### ISSUE THREAD

**Issue by SDCFWM** [jenkinsci/lockable-resources-plugin#24]
Following the hard-coded timeout is for how long the resource might be queued(reserved) before it's acquired. 
Class LockableResource.java:
private static final int QUEUE_TIMEOUT = 5;
If the timeout is expired a resource will be unqueued from the queue and an empty resource will be acquired by plugin:
[lockable-resources] acquired lock on []
The possible workaround might be to increase the timeout to some significant value.
However, it does not fix the issue. Plugin should check if acquired resource is empty and somehow react, for example, ask to acquire a resource one more time.

**Comment by jimklimov** [comment]
I think this is not a problem currently, a job can be blocked for hours waiting for a resource.
Looking at comments elsewhere, the timeout may be on the queue processing code - that a verdict about a job must be returned quickly (ready to execute or not?), as addressed by e.g. #171 to cache scripted verdicts that can take time to collect.
