### ISSUE TITLE
make /lockable-resources /api accessible

### ISSUE THREAD

**Issue by kddubb** [jenkinsci/lockable-resources-plugin#262]
### Dependencies

None

### Feature Request

With a couple minor changes, we can enable the standard /api API to retrieve lockable resources as JSON or XML.  This has been very helpful for my deployment.  Here is a PR with the changes:

https://github.com/jenkinsci/lockable-resources-plugin/pull/256

**Comment by jimklimov** [comment]
Recently merged, closing the issue.

Just in case: is #103 related to this?
