### ISSUE TITLE
Normalizing tabs and spaces

### ISSUE THREAD

**Issue by gaspardpetit** [jenkinsci/lockable-resources-plugin#292]
### What feature do you want to see added?

The .editorconfig has the folloging property:

```
[*.{html,java,jelly,xml}]
indent_style = space
indent_size = 2
```

Which indicates that files should be using 2-space indentation. In reality, several files are using tabs, making this project difficult to work with.

Would it be possible to normalize everything? I'm aware it might force current PR to be in whitespace conflict, but in the long run it will make contribution and merges easier.

I'm happy to provide a PR for this if I get a OK from the maintainers.

Cheers (and sorry to be that guy complaining about whitespaces)

**Comment by gaspardpetit** [comment]
Sent the PR for this, it just took a minute: https://github.com/jenkinsci/lockable-resources-plugin/pull/293

I notice there are several other minor violations of the Google Java Code standard - the most obvious ones are:

https://google.github.io/styleguide/javaguide.html#s4.4-column-limit

**Comment by jimklimov** [comment]
Merged
