### ISSUE TITLE
Allow multiple locks on resources based on attribute

### ISSUE THREAD

**Issue by bgalamb** [jenkinsci/lockable-resources-plugin#302]
### What feature do you want to see added?

Adding dynamic attributes to lockable resources would be very beneficial parallelising and speeding up exection by allowing every job who needs resource with same setup to run in parallel.
Use case: 
- we have 1 lockable resource with label : autotest_server
- jenkins job (nr1) want to `lock(label: autotest_server)`, perform long taking setup process: installing and boot backend (8 mins) **v1.2.3** and then run **test suite A** eg: 2 mins
- jenkins job (nr2) want to `lock(label: autotest_server)`, perform taking setup process: installing and boot backend (8 mins) **v1.2.3** and then run **test suite B** eg: 2 mins
- jenkins job (nr3) want to `lock(label: autotest_server)`, perform long taking setup process: installing and boot backend (8 mins) **v1.2.3** and run **test suite C** eg: 2 mins

As of now they would run sequentially even though all jobs basically require the same machine/installation.

1. lock() -> job nr1 (10 mins) -> unlock() 
2. lock() -> job nr2 (10 mins) -> unlock()
3. lock() -> job nr3 (10mins) -> unlock() 

If attribute during `lock(label: autotest_server, attribute: v1.2.3)` was added to the resource, and this attribute would allow lock even if resource is busy. Each job who wants to lock this label and attribute `lock(label: autotest_server, attribute: v1.2.3)` could reuse the same resource and run in parallel. As per the example above it would be 10 mins of total time execution. Attribute would be removed from the resource when all locks are released.

**Comment by gaspardpetit** [comment]
I think this would be useful to us as well - I was initially confused by the name `attribute`, may I suggest assigning an `id` to a lock? This would become:

So if I understand this feature correctly, when specifying an `id` when locking:
 - if there is a candidate satisfying with a matching id, share the lock
 - if there is no candidate, acquire a new resource and set the `id`

**Comment by bgalamb** [comment]
Yes, Exactly. This feature is very useful if you lock the resource and execute something which takes long time.

At our company we setup lockable resources to mirror prod like "test" machines. And this way we can execute API tests , regression tests and UI tests together in parallel.

I needed to add a little bit of extra logic to the pipelines (kind of semaphore) to perform initialisation only once across different jobs. We are calling a child "setup" job with identical parameters ($param.version) with await = true.

There is no additional steps needed for teardown. Lock will be released and attribute (=key) will be cleaned when last job locking the resource finished.
<img width="1773" alt="Screenshot 2022-02-10 at 10 28 43" src="https://user-images.githubusercontent.com/14314062/153383049-04eaf920-e286-46dc-94eb-bad2d2308721.png">

Sure I can change the naming!
I will fix it in PR https://github.com/jenkinsci/lockable-resources-plugin/pull/303
