### ISSUE TITLE
Lock Extra Array Variable returns csv list in order defined 

### ISSUE THREAD

**Issue by ghost** [jenkinsci/lockable-resources-plugin#319]
### What feature do you want to see added?

When locking via options in declarative, we can lock multiple resources by using the extra option and passing in an array of resources, we can also define a variable to get back a comma separated list of all the resources locked.

HOWEVER, the comma separated string of locked resources is not in the order at which the user defined, it seems to be in a random order or in an order of acquired lock, can we simply return the list in the order that the developer passed in ? 
<img width="788" alt="Screen Shot 2022-05-11 at 1 28 03 AM" src="https://user-images.githubusercontent.com/10914325/167775778-1df3fc9f-6f4c-460b-9bd5-8c10afee5951.png">

**Comment by jimklimov** [comment]
As a shot in the dark, this seems related to PR #301 (and/or further refactoring due after it) which changed the API from List to Set to guarantee uniqueness in a natural manner. CC @gaspardpetit

**Comment by gaspardpetit** [comment]
I agree, this should now be resolved with the #301

**Comment by mPokornyETM** [comment]
Becaue the automatic test tested exact this scenario and it is green I will cose this issue now.
