### ISSUE TITLE
Lock resource if match the sequence of multiple labels 

### ISSUE THREAD

**Issue by oleg-kondaurov** [jenkinsci/lockable-resources-plugin#335]
### What feature do you want to see added?

I have 3 resources:
Resource - Server_1, Labels - Debian, Server, HTTP
Resource - Server_2, Labels - Debian, Server, FTP
Resource - Client_1,  Labels - Debian, Client, FTP

I want have possibility to lock resource based the sequence of labels. For example Server + FTP

**Comment by jimklimov** [comment]
I believe this is already possible by use of label expressions?
In any case, for anything more complex you can use a groovy expression selector (like selecting a server that is currently pingable).

**Comment by oleg-kondaurov** [comment]
> I believe this is already possible by use of label expressions?

@jimklimov Do you mean a label conditions? It looks, it may be used only in `agent` section:
https://www.jenkins.io/doc/book/pipeline/syntax/#agent-parameters 

I can't use it with lock:
```
    options {
        lock(
            quantity: 1,
            label: '${DUT_MODEL} && BLE_Bridge',
            variable: "DUT_LOCKED"
        )
```
Got such error:
```
java.lang.IllegalArgumentException: The label does not exist: UDW && BLE_Bridge
	at org.jenkins.plugins.lockableresources.LockStepResource.validate(LockStepResource.java:88)
	at org.jenkins.plugins.lockableresources.LockStep.validate(LockStep.java:141)
	at org.jenkins.plugins.lockableresources.LockStepExecution.start(LockStepExecution.java:41)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
...
```

**Comment by jimklimov** [comment]
So indeed, sorry for misleading. I guess projects I've worked with had libraries extending the lockable resource functionality (dealing with LRM intimately) for so long that I forgot there was a difference. 

Looking at https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/main/java/org/jenkins/plugins/lockableresources/LockableResource.java#L176-L186 and https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/main/java/org/jenkins/plugins/lockableresources/LockableResourcesManager.java#L149-L174 it seems that indeed the plugin code maintains the original space-separated string as the list of labels, which it then splits for queries, like to know what individual labels exist (e.g. count resources that provide a label, count how many are available) and to look for which resource instance matches a single label.

I think PR #309 gave me the impression that a more advanced functionality is already here. That and other reviews stalled on my side with the turbulence of this year :(

**Comment by oleg-kondaurov** [comment]
> I think seeing PR #309 some time ago gave me the false-memory impression that a more advanced functionality is already here. That and other reviews stalled on my side with the turbulence of this year :(

PR #309 is exactly what I need. Didn't see it earlier.

**Comment by jimklimov** [comment]
For completeness, I think some of our jobs used the "groovy script matcher" which is called for every resource, does custom magic and decides (true/false) if that resource is what you want for the run. In our case it checked if an appliance to test on is alive. In yours it can check some complex logic about having these labels (and not having those) for example.

**Comment by mPokornyETM** [comment]
@oleg-kondaurov was the answer helpful? If yes it will be shifted to documentation to provide examples with groovy  matching.

**Comment by jimklimov** [comment]
@mPokornyETM : well, I think it can be both. A short-term solution via documentation and examples - note that there are overheads and other inconveniences for using the flexible groovy matcher.

And a long-term solution for this probable popular use-case, to pick up the label parser from build agent selection and use it here :)

**Comment by mPokornyETM** [comment]
> And a long-term solution for this probable popular use-case, to pick up the label parser from build agent selection and use it here :)

Yes, that is exactly, what I want do. I thing, I put somewhere the same notice (there are many similar issues / PRs). Therefore I will create new issue now and link all the similar things there, so we can close it and remove all the 2 years old opened issues.

**Comment by oleg-kondaurov** [comment]
@mPokornyETM Sorry, I didn't check it as PR is already not merged

**Comment by mPokornyETM** [comment]
will be handled in #428

**Comment by mPokornyETM** [comment]
> @mPokornyETM Sorry, I didn't check it as PR is already not merged

No problem, it's not your job to check if the PR is open or not ;-) You are not the maintainer here. But you can be, when you want ;-)

**Comment by mPokornyETM** [comment]
See #428
