### ISSUE TITLE
Ability to disable lock persistence on every step (support for performance-optimized pipeline durability)

### ISSUE THREAD

**Issue by mdealer** [jenkinsci/lockable-resources-plugin#338]
### What feature do you want to see added?

Currently the plugin insists on writing the lock XML file (calling LockableResourcesManager.save) every time we do something to a lock, but:

- Freestyle jobs are not persistent, not sure what meaning persistent lock count has here
- Pipelines in performance-optimized (PERFORMANCE_OPTIMIZED) durability mode are not persistent either, so same in this case.

There is a major performance bottleneck on heavy parallel pipelines because XML serialization runs through the slow XStream and all pipelines share the lock manager.

**Comment by mPokornyETM** [comment]
I like it. 👍  maybe we shall also allow it in the lock step or In resource configuration to handle which locks are necessary to save.

**Comment by mPokornyETM** [comment]
To keep it more independent from Jenkins core, I will propose to add new global config 'rememberState' and also add it to step lock().
It will be much more flexible for end users. 

Note for developer. It must work also in JCaC

**Comment by mPokornyETM** [comment]
@mdealer Hi, good news. There is new PR #516 which can solve this issue for you. You need only to set one system property and it will works.
It was good idea. THe plugin in my instance is much more faster.
