### ISSUE TITLE
Modernize plugin: Add a Jenkinsfile to evaluate the plugin and its pull requests on ci.jenkins.io

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#344]
follow this steps https://www.jenkins.io/doc/developer/tutorial-improve/add-a-jenkinsfile/

**Comment by gounthar** [comment]
I'm afraid it already [exists](https://github.com/jenkinsci/lockable-resources-plugin/blob/master/Jenkinsfile).

**Comment by mPokornyETM** [comment]
Thx, I know, I want only do it like a check-list and test response time. So we can close it.
