### ISSUE TITLE
Modernize plugin: Update the parent pom to use the most recent features of the Jenkins plugin build environment

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#345]
### What feature do you want to see added?

follow this instructions
https://www.jenkins.io/doc/developer/tutorial-improve/update-parent-pom/

**Comment by gounthar** [comment]
I think this one is already done: https://github.com/jenkinsci/lockable-resources-plugin/blob/master/pom.xml#L8
