### ISSUE TITLE
Modernize plugin: Update the SCM URL to replace a reference to an unsupported git communictions protocol

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#347]
### What feature do you want to see added?

follow instruction
https://www.jenkins.io/doc/developer/tutorial-improve/update-scm-url/

**Comment by mPokornyETM** [comment]
closed by #233

**Comment by gounthar** [comment]
I think this one is already done: https://github.com/jenkinsci/lockable-resources-plugin/blob/master/pom.xml#L51

**Comment by mPokornyETM** [comment]
correct
