### ISSUE TITLE
Modernize plugin: Add a link to “Report an Issue” so that users know the correct location to report bugs, enhancements, and security issues

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#353]
### What feature do you want to see added?

follow instruction
https://www.jenkins.io/doc/developer/tutorial-improve/add-a-link-to-report-an-issue/

**Comment by niranjanib** [comment]
Hi @mPokornyETM , I can pick this issue if it is still up for grabs.
