### ISSUE TITLE
Modernize plugin: Convert translations

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#356]
### What feature do you want to see added?

follow instruction
https://www.jenkins.io/doc/developer/tutorial-improve/convert-translations/

**Comment by gounthar** [comment]
Next step would maybe be using [Crowdin](https://crowdin.jenkins.io/).
https://www.jenkins.io/doc/developer/crowdin/crowdin-integration/

**Comment by mPokornyETM** [comment]
Look great. I want open an extra issue for translations, because et the moment there are many hardcoded texts.  But we can continue here. I newer use that. Probably need more help.

**Comment by mPokornyETM** [comment]
I have created the Crowdin localization for lockable-resources request and added @gounthar  as admin to. I hope it is fine for you.

https://github.com/jenkins-infra/helpdesk/issues/3208

**Comment by mPokornyETM** [comment]
'Convert translations' is not necessary, because we have no lang-mutation. Except one FR translation, but the one looks to be fine (no mvn warnings)

**Comment by mPokornyETM** [comment]
our crowdin ID is 26
