### ISSUE TITLE
Modernize plugin: Move description 

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#357]
### What feature do you want to see added?

follow instruction
https://www.jenkins.io/doc/developer/tutorial-improve/move-description-to-index/

**Comment by MarkEWaite** [comment]
> @MarkEWaite we use the file src/main/resources/index.jelly. but I have a question. Shall / can this file use localisation? 🤔

I don't know if it will be used if it is localized.  Good question that I can't answer

**Comment by mPokornyETM** [comment]
OK. In that case 8st this issue done. Thx
