### ISSUE TITLE
Flaked tests on LockStepTest

### ISSUE THREAD

**Issue by jlrigau** [jenkinsci/lockable-resources-plugin#37]
Sometime test failures occurs on `LockStepTest` and for avoiding the build to fail flaked tests have been allowed through Maven Surefire Plugin.

Instead of allowing flaked tests it could be a better strategy to find the reason why the test fail and fix the root problem.

Any idea about these test failures?

https://jenkins.ci.cloudbees.com/job/plugins/job/lockable-resources-plugin/101/console
https://jenkins.ci.cloudbees.com/job/plugins/job/lockable-resources-plugin/102/console

**Comment by amuniz** [comment]
Please, use [JIRA](http://issues.jenkins-ci.org) to report issues on `lockable-resources` component.

**Comment by jlrigau** [comment]
Related issue in Jira: https://issues.jenkins-ci.org/browse/JENKINS-37689
