### ISSUE TITLE
Seen "java.lang.IllegalArgumentException: The label does not exist: <>" when label is present

### ISSUE THREAD

**Issue by satya-alapati-einfochips** [jenkinsci/lockable-resources-plugin#399]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.332.3
  lockable-resources-plugin: 2.14
  ```

</details>

Added resource and label details using createResourceWithLabel ( `createResourceWithLabel(ResourceName, LabelName)` )
Then while locking the device ( `lock(label: resourceLabel, quantity: numOfDevices))` ) seen the below issue,
`java.lang.IllegalArgumentException: The label does not exist: Device-17`

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins CI

### Reproduction steps

Seen issue during CI execution

### Expected Results

Shouldn't see this issue

### Actual Results

Seen `java.lang.IllegalArgumentException: The label does not exist: Device-17` issue

### Anything else?

1. Using lockable-resources-plugin `2.14`, Will upgrading lockable-resources-plugin to version `2.18` solve this problem?
2. Error message says `The label does not exist:` which is confusing as we have labels for Jenkins nodes. Could you change it to `The resource label does not exist:`, As it is getting called as resourceLabel [here](https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/main/java/org/jenkins/plugins/lockableresources/LockStepResource.java#L133)

**Comment by mPokornyETM** [comment]
1. Can you please provide code snippet how you create the resource with labels?
When you use configuration page or JCaC yml file it shall works as well.
2. Yes, that minor change. (Maybe you will contribute and create your first PR ;-) )

**Comment by mPokornyETM** [comment]
One not for further changes here. The hardcoded texts in form validation shall be moved in to properties files (for localizations)
