### ISSUE TITLE
Once a lockable resource is created, how do I remove it (housekeeping issue)?

### ISSUE THREAD

**Issue by rbellamy** [jenkinsci/lockable-resources-plugin#40]
I've been using the Lockable Resources plugin, and during testing created some lockable resources that I no longer need - how do I remove them completely?

**Comment by lookAtThat** [comment]
I'm fairly certain you can delete resources in the System configuration.

**Comment by rbellamy** [comment]
Yep, found them - should have closed this issue. Thanks!
