### ISSUE TITLE
Lockable Resources "Show xxx entries" selection box option to change default entri

### ISSUE THREAD

**Issue by FredRaw** [jenkinsci/lockable-resources-plugin#404]
### What feature do you want to see added?

It would be practicle to have the option to select the default number of entries shown in the listview. I would like to have 100 instead of 10, but some others might want to have 50 etc.. The default selection should be saved for the next time you open the view.

![lockable](https://user-images.githubusercontent.com/48514461/203004316-2aff1286-104c-48b6-8cf9-1c9c421e3a73.PNG)

**Comment by mPokornyETM** [comment]
this is related to https://github.com/jenkinsci/data-tables-api-plugin
In worst case can be done by some workaround by in this plugin by javascript

@FredRaw  can you pls ask in the data-tables-api-plugin community. Maybe is there some solution per hand. It will be great help to me (little overstress at the time)+

**Comment by FredRaw** [comment]
Thanks for your quick reply @mPokornyETM! I tried to figure out how to ask a question in the data-tables-api-plugin community.. however, I am just to noob to be able to do that unfortunately..

**Comment by mPokornyETM** [comment]
Probably use Gira issues. https://plugins.jenkins.io/data-tables-api/
But I think you can skip it, because it shall be done by dataTable call on our side.
We need *only* find correct example / solutions here https://datatables.net/examples/index

But look this is nice idea, maybe it solve also this issue

https://datatables.net/examples/basic_init/state_save.html

**Comment by mPokornyETM** [comment]
@FredRaw   Maybe you want contribute and try to change it (look here https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/main/resources/org/jenkins/plugins/lockableresources/actions/LockableResourcesRootAction/index.jelly#:~:text=jQuery3(%22%23lockable%2Dresources%22).DataTable,%7D)%3B)
