### ISSUE TITLE
First adopters complaints about new Lockable Resources Data Tables UI

### ISSUE THREAD

**Issue by jimklimov** [jenkinsci/lockable-resources-plugin#411]
### Jenkins and plugins versions report

Jenkins 2.361.4
Lockable Resources 1069.v726298f53f8c 

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux CentOS

### Reproduction steps

Had LR 2.18
Updated to current

Several complaints collected:

1. Sorting order (by value) vs. resource definition order (set by admin)
2. Items per page vs. refresh
3. Sorting order vs. refresh
4. Filtering vs. refresh

### Expected Results

UI usable (per habits and expectations spec for the team)

1. Sorting order (by value) vs. resource definition order (set by admin)

Resources most used by team members (e.g. SUTs left "stolen" for post mortems), as opposed to infrastructural and ephemeral resources, are on top of the list. Definition order (from global config / XML) with older tables ensured that.

2. Items per page vs. refresh
3. Sorting order vs. refresh
4. Filtering vs. refresh

If a choice is made (e.g. 100 items, Sort by name, filter to show items with "X" in... which field?) it is remembered when page is refreshed. Ideally it would be remembered for the user session/account so the cosmetic choice is not required every time you open the list (maybe except the filter).

### Actual Results

1. Sorting order (by value) vs. resource definition order (set by admin)

There does not seem to be a way to disable sorting by column values to revive sorting by definition order. This is almost a show-stopper for the team who now have to hunt for their dozen dedicated SUTs in the middle of hundreds of entries.

2. Items per page vs. refresh

When page refresh happens, it shows 10 items again

3. Sorting order vs. refresh

When page refresh happens, it shows default sorting again

4. Filtering vs. refresh

When page refresh happens, it shows all items again

### Anything else?

* Fallout of #375

* Similar concerns were raised in #404

* Same inconvenience issues with the lower table (list of labels and their usage)

* Default sorting order seems to have no real pattern to it. It does apply "Status" to put currently reserved entries on top, and according to header icons it then probably sorts by "Resource" name, but in fact the reserved entries are arranged randomly. Those currently free do seem to be alphabetically sorted by name.

* Table does not show the recently introduced timestamp field which was in 2.18 UI.
    * This info is useful, should be exposed.
    * Maybe sorting of reserved resources takes it into account "quietly"?

* Max of 100 items (or any max) may be inconvenient to some people. Can an option be added to show everything on one page?

* A suitable solution for teams that relied on old behavior may be to revive the old UI as a separate link and page, allowing more time and flexibility to perfect the new one.

**Comment by jimklimov** [comment]
While looking at #375 changes, I saw it reference `reservedTimestamp` quite a lot in the updated `index.jelly` file, mostly in tooltip preparation. So maybe the plugin lost ability to discover/track these timestamps?..

Tooltips look funny without the actual date pasted in:

![image](https://user-images.githubusercontent.com/1636756/203530716-b7b6562e-d6ca-41ec-ad75-ccbbbbf9317f.png)

**Comment by mPokornyETM** [comment]
About data-table properties and #404 I am currently in contact with data-tables-plugin team. I hope we found solution quickly.

**Comment by major-sam** [comment]
Attach please dark theme font color bug
![image](https://user-images.githubusercontent.com/13558875/203560584-993c725b-6967-4083-84ad-ff1f2eefd73b.png)

**Comment by jimklimov** [comment]
I think the issue highlighted by @major-sam comes from direct style (color etc) used in `index.jelly` after update, rather than CSS references. But yes, an issue too (just not one I'd have seen here) :)

**Comment by jimklimov** [comment]
![image](https://user-images.githubusercontent.com/1636756/203565388-f24a4599-c96e-454d-909f-88f15d6a38fa.png)

Sorting of the lower table (free resources' stats) is odd. It seems to forcibly prioritize partially-available vs. fully-available (100% or not) as part of sorting, and sorts the numbers alphabetically (1, 2, 40, 5 ...)

**Comment by mPokornyETM** [comment]
> While looking at #375 changes, I saw it reference `reservedTimestamp` quite a lot in the updated `index.jelly` file, mostly in tooltip preparation. So maybe the plugin lost ability to discover/track these timestamps?..
> 
> Tooltips look funny without the actual date pasted in:
> 
> ![image](https://user-images.githubusercontent.com/1636756/203530716-b7b6562e-d6ca-41ec-ad75-ccbbbbf9317f.png)

Hi, When I reserve it manually it works.
![image](https://user-images.githubusercontent.com/89339813/204112587-80aefdbb-ad2a-4f05-bc62-1a865be56739.png)

But I see when it is reserved by the config file I got same result as you. This will be fixed ASSAP. But only to be sure, can you tell me how you reserve the resource? Because I do not think, that you use config file for that.

**Comment by jimklimov** [comment]
Čus! Regarding reservations - I think on the deployment I'm looking at they are mostly happening with custom pipeline scripting which taps into the LockableResourcesManager directly (so calling Java methods rather than pipeline steps to reserve/unreserve/etc.). Part of the reason being to let lockable resources be passed around between stages and jobs - so SUTs are not freed and recycled by virtue of ending a small `lock{}`ed stage. Another reason is to optionally leave "broken" SUTs for post-mortems after the job ends, if devs want to investigate how a test failed on a standard setup when they can not reproduce the situation locally.

Either way, if there is indeed a new method to set the reservation timestamp, which is not called as part of Java methods to lock/unlock/reserve/unreserve, then it is possible that the custom pipeline logic here is not calling it either and that would be how the value is absent or empty.

So if it is a case of "we shot ourselves in the foot" and is hard to cleanly amend in the plugin (e.g. not write "ago" if the value is absent), and the situation can not be reproduced by "proper" intended usage of the plugin - let it be (maybe comment/document that method X should be called to set the value). If however users honestly using the plugin can get into this situation, then it is more of a bug to address...

**Comment by mPokornyETM** [comment]
thx, I see. in that case I will improve this "fix" also for other states (but in other way, I do not like the many of jelly duplicated codes).

https://github.com/jenkinsci/lockable-resources-plugin/blob/7f0f318adbac5d53ae14feab541517d2ecbf8f86/src/main/resources/org/jenkins/plugins/lockableresources/actions/LockableResourcesRootAction/index.jelly#:~:text=null%7D%22%3E-,%3Cj%3Aset,%3C/j%3Aif%3E,-%3Ctd
