### ISSUE TITLE
Use the label parser from build agent selection.

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/lockable-resources-plugin#428]
### What feature do you want to see added?

There are many solutions around the world using resource-labels. Many of them need more sophisticate search solution.
Therefore we shall pick up the label parser from build agent selection and use it here. This will improve plugin usage and close many similar opened issues / PRs.

**Comment by chickenkiller** [comment]
This is exactly what I hoped for ! Using the exact same logic as for nodes labels. We are used to it and it's powerful!

**Comment by mPokornyETM** [comment]
@chickenkiller in that case you are welcome to implement it ;-)

**Comment by chickenkiller** [comment]
I'm so bad at Java! But I can have a look when I have time.

Le ven. 9 déc. 2022 à 18:27, Martin Pokorny ***@***.***> a
écrit :

**Comment by g3n35i5** [comment]
@chickenkiller @mPokornyETM any updates on this? I'd love to see this feature.

The PR #309 looks very promising to me but the tests are failing. Do you think its worth the effort to sync the current master into the feature branch and fix all issues until it works?

**Comment by mPokornyETM** [comment]
Ouch.
1. I try to find out, how it is done in Jenkins (in the step node() ). After my first analysis I figured out, that It is not so easy. Because in the step node() will be search for 1 item, and we need here many of items (multiple resources). After them I want to ask community about possible solution, but I forgot it.,
2. When we want to merge PRs like #309 it will be very hard to maintain it here all of the possible filters.
3. When you want to work on #309 I will propose to create new branch and bring only changes there. Working on original branches is more or less not possible. See also #394 
4. Maybe we shall open new discussion here in git-hub like 'Lockable-resource filtering' or something like that, to provide all of the current possibilities, wishes and feature request there. So we can see what is done, and what shall be done, in which direction we shall go ...

Why I do not work on this?
I does not see any reason currently. You can use the groovy filter as well. That means you can do more complex (but also a easy one) filter logic. In that case I see this issue like a nice-to-have. Please correct me, when it is for some-body important.

@chickenkiller Do you want to contribute on this idea?

**Comment by g3n35i5** [comment]
> I does not see any reason currently. You can use the groovy filter as well. That means you can do more complex (but also a easy one) filter logic. In that case I see this issue like a nice-to-have. Please correct me, when it is for some-body important.

Thanks for your reply! Can you please explain your groovy filter method? I didn't see any documentation on this in this plugin. If there's a way to do resource filtering like `give me N resources that have the labels A and B but not C` I'd be happy if you could show me a way to do it.

**Comment by mPokornyETM** [comment]
Strange. I didn't find any example. Just the implementation 'SecureGroovyScript'. But before we provide the example, we shall write few tests. Only to be sure, it works as expected.

**Comment by chickenkiller** [comment]
> @chickenkiller Do you want to contribute on this idea?

I don't have much time, sorry, but I'll try to give you my findings so far anyway.

**Comment by chickenkiller** [comment]
> Strange. I didn't find any example. Just the implementation 'SecureGroovyScript'. But before we provide the example, we shall write few tests. Only to be sure, it works as expected.

If I recall correctly I already tried to use the groovy filter, but I think the content if filtered out when you want to use pipelines. I can't remember where and why in the code though... But there was a kind of security put in place somewhere.

**Comment by siddjere** [comment]
@mPokornyETM Our team is really interested in this feature. We have hundreds of nodes which can have multiple labels like A, B, C and as @g3n35i5 mentioned above we need a similar logic to filter out if a node which matches A and B is available. This is similar to how we use the groovy node step by specifying node('A&&B'){ Do something}. Currently our team has to create a dummy node by specifying a hostname in the configuration which eventually creates a lot of java agent processes on that node. Hence, moving to lockable reosurce plugin is the best way for us to tackle all the downsides

**Comment by mPokornyETM** [comment]
In that case shall be this issue an hot topic ;-) I will do my best. This week it is hard, maybe next one.

**Comment by mPokornyETM** [comment]
Good news. I find the solution. Currently works here https://github.com/mPokornyETM/jenkins-lockable-resources-shared-library/blob/feature/step/vars/lockNode.groovy

I know it must be documented and also automated tests are missing, but in my pipe works.

Somebody interested.  Fork the repo and try it.
