### ISSUE TITLE
Node dependend resources

### ISSUE THREAD

**Issue by tt-togi** [jenkinsci/lockable-resources-plugin#44]
I need to create resources that are node dependend. That means a job must pick a target node where the requested resource is available. Does anybody else has similar needs?
I consider extending this plugin but I worry that the effort would possibly exceed my coding skills.

**Comment by nikolaykasyanov** [comment]
It's already possible when using Pipelines:

```groovy
lock("whatever-resource-${env.NODE_NAME}") { ...
```

It would be great to have it a regular way as well, though.

**Comment by chrisaaaaa** [comment]
Sorry for the hijack...

I have a system based on chained jobs with per-node resources, before I go to all the trouble of converting to pipelines can it handle this?

2 Nodes, 1 with one excutor (the master, dual i7), one with 2 executors (hex i7), each with one HW item of type A and B.
Multiple jobs of type A or B, each build requires exclusive access to the related HW.

I want to avoid 2 A's or 2 B's running on the multiple executor node.

?

**Comment by darius-m** [comment]
Pull request https://github.com/jenkinsci/lockable-resources-plugin/pull/15 provides this feature, if I understand your needs correctly. It has been open for quite a while now, and I've updated it for the current master, so it should work properly.
