### ISSUE TITLE
The order of the resources is no more respected in "Lockable Resources"-page

### ISSUE THREAD

**Issue by karniemi** [jenkinsci/lockable-resources-plugin#460]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins 2.375.2
1123.v4002ee23c671 
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

For example:
* add Lockable Resources in Jenkins Management
* drag and drop to change the order

### Expected Results

"Lockable Resources"-page should show the lockable resources in the same order the user has them in Jenkins Management

### Actual Results

The order is not the same as in Jenkins Management

**Comment by karniemi** [comment]
This is a bit disturbing, because we have a specific order for our resources to make them visualized nicely for our devs. Also we have used dummy-resources to act as headers for grouping the resources in the Lockable Resources status page.

**Comment by mPokornyETM** [comment]
Yes.  This is known, when you sort columns in the table.  It shall be fixed in data-table plugin.  A workaround is to clear your browser global- storage

**Comment by mPokornyETM** [comment]
@uhafner is it planned to fix it the api? When not we can discuss it, what shall be the best solution and maybe I find time to fix it.

**Comment by uhafner** [comment]
I'm not sure if I can follow. What order do you mean? The order of the columns? The ordering (sorting) of the rows? A screenshot would help.

**Comment by mPokornyETM** [comment]
When it's not planned for the api I can create new settings for lockable-resources-plugin like enable-user-ordering. But it will be very tricky to implement it. And I don't like hack solutions. 😒

**Comment by mPokornyETM** [comment]
I think this is the line
https://github.com/jenkinsci/data-tables-api-plugin/blob/5f0deb21ed2688aa26cb2a11136ef2c54c8f9988/src/main/webapp/js/table.js#L161
It will be fine to provide table option to skip it. 

Of course this one too 
https://github.com/jenkinsci/data-tables-api-plugin/blob/5f0deb21ed2688aa26cb2a11136ef2c54c8f9988/src/main/webapp/js/table.js#L20

**Comment by uhafner** [comment]
I see. Adding an option should be not too complex, feel free to provide a PR. Since a lot of users like storing of the sorting order it would make sense to make that user configurable using a UI configuration somehow.

BTW: you can use a data table without using the jelly tags. Then you loose some features added by me but then you can use the table as such.

**Comment by mPokornyETM** [comment]
Thx for your answer.  I will contact you next week to discuss "somehow" 😇

**Comment by karniemi** [comment]
To visualize, we have defined lockable resources in this order in the configuration. ( I left labels out for simplicity of the example). 
```
--------- system testlabs
lab1
lab2
lab3
--------- sandboxes
sandbox1
sandbox2
--------- PET
petlab
--------- other lockables
```
Earlier plugin-versions respected this order in "Lockable Resources"-page visualization, new versions don't.

**Comment by mPokornyETM** [comment]
thx

what about to make something like this

```
system-test-labs/lab1
system-test-labs/lab2
system-test-labs/lab3
sandboxes/sandbox1
sandboxes/sandbox2
petlab
```

and it will be "grouped" by '/'  like in tree.
```
system-test-labs
   lab1
   lab2
   lab3
sandboxes
  sandbox1
  sandbox2
petlab
```

And this delimiter shall be parametrized. This will be nice UI feature. 
But as first, I will try to make enable-sorting configurable.
