### ISSUE TITLE
Re-populate the search query input box after performing an action

### ISSUE THREAD

**Issue by yandemontreal** [jenkinsci/lockable-resources-plugin#461]
### What feature do you want to see added?

The search box is a very important part of the UI now that the page size is limited to 100 items. However when there is a need to reserve/steal/release (henceforth 'action') multiple resources in a row, it's cumbersome to have to re-enter the search query after every action.

The search query should be automatically re-populated after an action, until the user clears it or comes back to the lockable resource main page by a means other than a button action (e.g. clicking on the Lockable Resources link in the left-hand side menu).

**Comment by mPokornyETM** [comment]
@uhafner I didn't find any solution in data-tables plugin. Has you any idea? Or shall be implemented here? I can use same solution as you do to store sorting, paging ... .

**Comment by jimklimov** [comment]
@mPokornyETM : I see you have progressed on data-tables part, is anything blocking a fix in lockable-resources? This bit me too now :)

**Comment by mPokornyETM** [comment]
There are an issue by plugin releases. It shall be fixed (yesterday I think) . I will test rthis changes today. We will see. Anyway I will post here feadback after them

**Comment by mPokornyETM** [comment]
@jimklimov  PR is ready for review https://github.com/jenkinsci/lockable-resources-plugin/pull/474
