### ISSUE TITLE
DSL lock by label doesn't reveal which resource was locked.

### ISSUE THREAD

**Issue by sheepdreamofandroids** [jenkinsci/lockable-resources-plugin#48]
The title says it all. How do I find out which resource(s) of a label was locked inside the lock step?

**Comment by sheepdreamofandroids** [comment]
The code revealed that there was no way to do it. I added a [pull request (#49)](https://github.com/jenkinsci/lockable-resources-plugin/pull/49) to retrieve the resource(s) using an environment variable. 

Please let me know what I can do to get this accepted quickly.

**Comment by ffiorentino-CBNL** [comment]
Quite useful feature!

**Comment by ffiorentino-CBNL** [comment]
@sheepdreamofandroids : I have found in here https://issues.jenkins-ci.org/browse/JENKINS-34268

Basically you could use in your pipeline:
echo org.jenkins.plugins.lockableresources.LockableResourcesManager.class.get().getResourcesFromBuild(currentBuild.getRawBuild())[0].getName()

I have tested and it works fine (note you have to approve several Signatures in the Jenkins scriptApprovall before this start to work).

You could consider to use this method meanwhile your PR (#49) is merged.

**Comment by staffanf** [comment]
This is essentially the same issue as https://issues.jenkins-ci.org/browse/JENKINS-40997
Using the previously proposed syntax with a variable might be better than https://github.com/jenkinsci/lockable-resources-plugin/pull/49 which use environment var.
Any way is better than none for me though.

**Comment by sheepdreamofandroids** [comment]
@ffiorentino-CBNL Thanks, that is really ugly but very useful  ;-)

@staffanf Are you sure MYVAR isn't an environment var? I don't know how to change a groovy var. I was thinking of returning the locked resource as a return value of the step but the value should be available within the block only, not outside it.

**Comment by staffanf** [comment]
@sheepdreamofandroids No, now that you ask, I'm not ;-) . I think putting it in the environment is probably just as good or better. Thanks for working on this, it will allow me to remove some sandbox warnings.

**Comment by sheepdreamofandroids** [comment]
Hi @amuniz , is there anything I can do to help you merge this PR?

**Comment by ffiorentino-CBNL** [comment]
@sheepdreamofandroids: I play a lot with pipeline lately. Moving the ugly code into a "Global Shared Libraries" and then use the function in my pipeline is a little less ugly solution since you don't have to approve a lot of script usage.

Basically means to create own DSL syntax that do some action which include the lock syntax.
I have follow this wiki https://jenkins.io/doc/book/pipeline/shared-libraries/ to get the idea.

Again this a workaround meanwhile the PR will merged it :)

**Comment by f-julian** [comment]
Hi looks like i have implemented the same feature with https://github.com/jenkinsci/lockable-resources-plugin/pull/50

Maybe we can merge our PRs? (Or some maintainer just chooses one...)

And i think this is https://issues.jenkins-ci.org/browse/JENKINS-40997

**Comment by troy-jacobson** [comment]
I'd like to add my vote for getting this enhancement released soon.  For one of my use cases, the prescribed workaround is not usable.  In that case, I'm doing parallel stages, and each stage wants to get a locked resource unique for that stage.  The workaround returns the same resource name for both stages.

I've successfully tested a patched version using PR#49 on our testbed Jenkins.

**Comment by armbraggins** [comment]
I'm in the same position as @troy-jacobson, using locks inside "parallel", except that I've successfully tested a patched version using PR#50

**Comment by kddubb** [comment]
+1

**Comment by mpm-bug** [comment]
I'd sure like to see this enhancement get released as well. I need this in a job I'm working on, and would prefer not to have to patch my Jenkins install.

**Comment by anthuwan13** [comment]
same here
