### ISSUE TITLE
Maintained badge is out of date

### ISSUE THREAD

**Issue by jimbudarz** [jenkinsci/lockable-resources-plugin#505]
### Describe your use-case which is not covered by existing documentation.

The "maintained" badge in the readme says "no! (as of 2022)".

[![Maintenance](https://img.shields.io/maintenance/yes/2022.svg)](https://github.com/jenkinsci/lockable-resources-plugin)

I guess this only updates once a year and needs to be changed manually to the 2023 version (though this way of flagging is a little crude)

[![Maintenance](https://img.shields.io/maintenance/yes/2023.svg)](https://github.com/jenkinsci/lockable-resources-plugin)

**Comment by akshaywakhare** [comment]
Hi, I would like to work on this.
