### ISSUE TITLE
Request: Delete resources after they haven been used

### ISSUE THREAD

**Issue by Mixermachine** [jenkinsci/lockable-resources-plugin#51]
Hy there,
I want to use this plugin to coordinate some of my tests in my pipeline.
There are MANY tests I need to coordinate.
Every test requires a lock ("Path-" + actualPath) { // do test} 
and therefore creates a lockable resource.
This is good for the moment, but after the test has been done this results in a list of over 50 (many more tests are going to be migrated to pipeline) more or less useless lockable resources that crowd the lockable resource list and make it unusable.
This makes finding a consistent lockable resource like 'testing on testing3' or 'prod_lock' very hard.

Is it possible to make resources temporary with lock (nameOfResource:String, diposeAfterUse:boolean) {}

Do you know another way to automatically dispose a useless lockable resource?

Thank you :)

**Comment by amuniz** [comment]
This would be covered by [JENKINS-38906](https://issues.jenkins-ci.org/browse/JENKINS-38906)
