### ISSUE TITLE
Move properties to child row

### ISSUE THREAD

**Issue by meeusen** [jenkinsci/lockable-resources-plugin#534]
### What feature do you want to see added?

If you have a couple of properties for each resource, the rows become quite wide, and you lose overview of the table. The properties could be moved to a child row (https://datatables.net/examples/api/row_details.html).

I've tried the basics, to hide the properties column and show it in the child row. This is available in https://github.com/meeusen/lockable-resources-plugin/tree/child-row, and this is what it looks like:

Collapsed:
![2023-07-09-211325_1528x334_scrot](https://github.com/jenkinsci/lockable-resources-plugin/assets/8501743/d3a97438-aa51-4def-919e-1e127c0683ee)

Expanded:
![2023-07-09-211437_1535x513_scrot](https://github.com/jenkinsci/lockable-resources-plugin/assets/8501743/39514975-cecd-446e-a0ae-aa069ebcfab5)

**Comment by mPokornyETM** [comment]
I like this change, can you pls provide PR? I will test it then. But I am until end of Juli on vacation.

**Comment by mPokornyETM** [comment]
as PR #539 has been finished
