### ISSUE TITLE
Can not lock on Labels in Free-flow jobs 

### ISSUE THREAD

**Issue by f-steff** [jenkinsci/lockable-resources-plugin#55]
[Originally documented here - probably with better formatting than here](https://wiki.jenkins-ci.org/display/JENKINS/Lockable+Resources+Plugin?focusedCommentId=118096018#comment-118096018)

Now added to Jenkins JIRA  [JENKINS-44388](https://issues.jenkins-ci.org/browse/JENKINS-44388) 

The current 2.0 version does apparently not work with labels, when used in a free-flow job!

I set up a small test scenario to play with, and it seems like waiting for resources works, but not waiting for Labels.
 
My tests below:
I used a resource named TEST, with two labels TEST_1 and TEST_2.
Looking at the available resources, it's reported that I have the "TEST" resource, and one instance of the two labels - as expected.
In a free-flow job, I enable This build requires lockable resources, and the tested the following four setups:

**Trial 1**
Resources = TEST
Number of resources to request = 0
Expectation: The resource TEST and all labels consumed during the test.
On execution:
The test project does not wait for anything.
None of the resources nor labels are reported used.
Note: This might be correct behaviour - provided 0 is used literal, unlike documented in the plugin: "empty value or 0 means all "

**Trial 2**
Resources = "TEST"
Number of resources to request = 1
Expectation: All labels on the TEST resource will be consumed.
On execution:
The test project does wait for the TEST resource and does consume all Labels.
 
**Trial 3**
Lable = "TEST_1"
Number of resources to request = 0
Expectation: The TEST_1 label will be consumed, leaving "TEST_2" available.
On execution:
The test project does not wait for anything.
None of the resources nor labels are reported used.
Note: This might be correct behaviour - provided 0 is used literal, unlike documented in the plugin: "empty value or 0 means all "

**Trial 4**
Lable = "TEST_1"
Number of resources to request = 1
Expectation: The TEST_1 label will be consumed, leaving "TEST_2" available.
On execution:
The test project does not wait for anything.
None of the resources nor labels are reported used.
Trial 4 is the error I'm really concerned about, as it seems to indicate that only resources can be taken, and not labels.

**Comment by per-bohlin** [comment]
I'm seeing the same thing.
Lockable resources plugin: version 2.0
Jenkins: 2.46.2
OS: Linux, Ubuntu 14.04 LT

I'm also seeing incorrect feedback in configuration page, that it can't find find label "a b" when trying to enter multiple labels "a" and "b".

My test is:
Create resource:
resource a1, label a
resource a2, label a
resource b1, label b
resource b2, label b

Free style job:
lock on label: a b
(Incorrect) error message that label "a b" can not be found.
is allowed to build, even if all resources are locked.

**Comment by per-bohlin** [comment]
@f-steff, have you reported the issues on jenkins official bug-tracker?
https://issues.jenkins-ci.org/browse/JENKINS-44141?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20lockable-resources-plugin

**Comment by f-steff** [comment]
@per-bohlin Oops. No. Mentioned on the plugins Confluence page, and here. But now also added to Jenkins JIRA as [JENKINS-44388 ](https://issues.jenkins-ci.org/browse/JENKINS-44388)
Thanks for checking and commenting.

**Comment by f-steff** [comment]
@per-bohlin Since you are also testing the plugin with free-flow jobs, could I trouble you to also look at [this bug report](https://github.com/jenkinsci/lockable-resources-plugin/issues/56), I've also made?

**Comment by TobiX** [comment]
Since the parallel Jira issue for this was closed, I'm closing this ticket also. Feel free to reopen if anything is still unclear.
