### ISSUE TITLE
Slash in name breaks navigation in lockable resource view for labels 

### ISSUE THREAD

**Issue by vtvz** [jenkinsci/lockable-resources-plugin#570]
### Jenkins and plugins versions report

  ```text
Jenkins: 2.414.2
OS: Linux - 5.4.0-1029
Java: 11.0.20.1 - Ubuntu (OpenJDK 64-Bit Server VM)
---
lockable-resources:1185.v0c528656ce04
  ```

### What Operating System are you using (both controller, and any agents involved in the problem)?

```text
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

### Reproduction steps

1. Create a resource named with label having slash. e.g. `frontend/signin`
2. Open "Lockable Resources" view
3. Click "Labels" tab
4. Click created resource label

### Expected Results

Page for clicked label

### Actual Results

 `HTTP ERROR 404 Not Found` page

### Anything else?

By default it opens these pages like that
`https://jenkins/label/frontend/signin/`
which produces this error.
But encoding slash with following JS code `encodeURIComponent('frontend/signin')` helps 
`https://jenkins/label/frontend%2Fsignin/`

**Comment by PayBas** [comment]
Feels like allowing `/` would be asking for major trouble.

Jenkins doesn't allow it for agent names.
![image](https://github.com/jenkinsci/lockable-resources-plugin/assets/3015760/2fb71768-cb0f-43c6-8cad-1110dee4f61f)

It would be better if the Lockable Resources plugin also blocks it.

**Comment by vtvz** [comment]
I use it because it allows me to use the same label as pipeline's name. I create job with path `$jobFullName` and 2-3 resources with names `$jobFullName/[1-3]` and label `$jobFullName` and this makes a trick:

```groovy
  options {
    lock(label: env.JOB_NAME, quantity: 1)
  }
```

It's very convenient and readable. 

Nevertheless, I prefer using this as is. But if you choose to gate it, I'll migrate

**Comment by mPokornyETM** [comment]
Probably, no more in scope of interest
