### ISSUE TITLE
Option to randomly assign a resource when requested by label

### ISSUE THREAD

**Issue by yandemontreal** [jenkinsci/lockable-resources-plugin#572]
### What feature do you want to see added?

It appears that currently if multiple instances of a resource exist and when requesting a resource by label, the _first available_ resource is assigned, based on its index.

It would be beneficial to offer to randomize the allocated resource, in cases like mine where these resources have a limited lifecycle. To even out the wear.

I think it would be acceptable to start with just a global parameter. Although _random_ is not more wrong than the current method, it should probably not be the default behavior as it could break other people's workflow if they unknowingly depend on some sort of induced determinism.

**Comment by PayBas** [comment]
```
lock(label: 'mylabel', resourceSelectStrategy: 'random') {
    // some block
}
```
Works for me.
> The strategy used to chose which available resources get locked. By default, the strategy will be "sequential" and resources are locked following the order in the lockable resources list. Set the strategy to "random" to randomize the order in which resources are locked.

**Comment by yandemontreal** [comment]
Apologies, I only looked at the LR Jenkins Plugin page. Thank you for highlighting this.

Should this feature request juste be transformed into a documentation update request?
