### ISSUE TITLE
Remove locks from the Lockable Resources Manager

### ISSUE THREAD

**Issue by jocelynduc** [jenkinsci/lockable-resources-plugin#60]
Hi,

We are using some Multibranch piplines and we are creating branch-specific locks. We now have hundreds of unused locks in our Lockable Resources Manager.

Is there a way to delete them or to clean this list at the end of a build? or to unpersist them in this list?

**Comment by witokondoria** [comment]
You could setup a nightly job as described on a [relevant Jira ticket](https://issues.jenkins-ci.org/browse/JENKINS-38906?focusedCommentId=315770&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-315770) or you could also apply the same resources modification as a pipeline cleanup stage. Just control the resource is already unlocked and noone is queued to use it (even then, concurrency problems might happen, treat this comment as a workaround)

**Comment by AaronDMarasco-VSI** [comment]
I tweaked https://gist.github.com/odavid/76b6874ed2b421b3eeb838aec0e9e040 and have a Jenkins job run every evening (not sandboxed) to remove locks with certain patterns:
```
def manager = org.jenkins.plugins.lockableresources.LockableResourcesManager.get()
def resources = manager.getResources().findAll {
    (!it.locked) && (
        it.name.startsWith("docker_rpminstalled") ||
        it.name.startsWith("docker-rpmbuild") ||
        it.name.startsWith("rpm-deploy")
    )
}   
resources.each {
    println "Removing ${it.name}"   
    manager.getResources().remove(it)
}
manager.save()
```

**Comment by Constantin07** [comment]
@AaronDMarasco-VSI Thanks for sharing. I'm getting `java.util.ConcurrentModificationException` exception when calling `remove` method with the latest Jenkins (2.164). Do you have the same ?

**Comment by AaronDMarasco-VSI** [comment]
@Constantin07 I never have, but others have warned me - see the comments on [JIRA bug JENKINS-38906](https://issues.jenkins-ci.org/browse/JENKINS-38906?focusedCommentId=353245&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-353245). As I noted there, my situation has very little chance of concurrency issues. Sorry I couldn't help more. In the second loop where the `remove` is being called, maybe it can be locked?

**Comment by Constantin07** [comment]
It looks like it doesn't allow to remove items from resource list while looping through it.

I just created another list to capture what to delete and then remove them in this loop.
Thanks for reply.

**Comment by medianick** [comment]
The original issue should be resolved by the ephemeral locks behavior released in https://github.com/jenkinsci/lockable-resources-plugin/releases/tag/lockable-resources-2.6

**Comment by TobiX** [comment]
Seems @medianick was faster spotting this then I was working through the open issues after the release :+1: 

Closing as fixed. Please reopen if there is something I didn't consider.
