### ISSUE TITLE
how to declare total available quantity in pipeline?

### ISSUE THREAD

**Issue by caphrim007** [jenkinsci/lockable-resources-plugin#63]
I see a lot of examples on how to use the lock resource to request quantities to lock,

```
lock(resource: '2GB-RAM', quantity: 2) {
...
}
```

but I havent found an example that declares how many total quantity for a particular resource there are.

Can anyone provide an example of that?

**Comment by troy-jacobson** [comment]
Are you looking for "Manage Jenkins > Configure System > Lockable Resources Manager"
or something different?

**Comment by caphrim007** [comment]
I think the declaration is the usage. You can include and empty closure and it will automatically create the resources

**Comment by birfincankafein** [comment]
This issue is still valid, there is no option for setting the total quantity of the resources can be locked, maximum.
