### ISSUE TITLE
Pipeline: Resource label as a variable

### ISSUE THREAD

**Issue by edupo** [jenkinsci/lockable-resources-plugin#68]
I want to pass the label of the locked resource as a variable to the scripts executed inside the step, but I couldn't find a clean explanation about.

Is this even possible?

```
stage("Test") {
  steps {
    lock(resource: 'test_hosts', quantity: 1) {
      sh 'ping <resource label>'
    }
  }
}
```

If not possible it would be a great feature.

**Comment by troy-jacobson** [comment]
This seems to be another request for a feature that myself and others have been asking for.

Look at the issue titled "DSL lock by label doesn't reveal which resource was locked".  It contains a workaround that you may be able to use.

**Comment by jimklimov** [comment]
IMHO the example for this use-case is flawed: the "label" describes some feature or type or resources, e.g. "printers" in the doc. Many resource instances can have the same label, so if you're testing some printing software - you can exclusively have some (any) device with a printer for your job. 

Also a resource instance can have many labels that you might match simultaneously or just one by one, to use the same resource in different jobs at different times (e.g. matching "linux & x86" vs. "linux & arm" for jobs where architecture matters, compared to "linux" vs. "windows" in another job that tests architecture-independent scripts or spellchecks texts or whatever, with tools available on Linux but not Windows in your farm).

In the OP's example you would "ping" the given instance of the resource, e.g. by its name (groovy variable whose name you define in the job which uses the lockable resources).

You may also be interested in #72 and #73 for examples with code you can copy-paste.

**Comment by amuniz** [comment]
I think you are looking for https://github.com/jenkinsci/lockable-resources-plugin/pull/49. I did not have the time to review it yet, will try to do it soon.

**Comment by meuter** [comment]
I'm in the exact same case as the one described by @edupo above. I'm eagerly waiting for the pull request #49 to be merged :-)

**Comment by TobiX** [comment]
Since #49 was merged a year ago, I consider this fixed
