### ISSUE TITLE
Feature Request: Show all jobs waiting for resource

### ISSUE THREAD

**Issue by Gentleman1983** [jenkinsci/lockable-resources-plugin#69]
Hi,
I have a problem. We have several hundred build jobs and e.g. sometimes they share the same resources, e.g. db or integration servers, deployment targets and so on. In the lockable resource list, I have listed all active locks, which job currently uses the lock and the possibility to lock or unlock the resource.

Is there any possibility to show the jobs waiting for the lockable resource or may you add a possibility to view this?

That would be great.

Yours

Christian

**Comment by sw** [comment]
This would also help us in deciding which pool of resource should be extended to improve throughput.

I.e. if a label corresponds to software licenses or hardware equipment, a long queue would indicate that more instances of the resource should be bought to enable more jobs to run in parallel.

On the web interface, the "Labels" table on the "Lockable Resources" page could be extended with a column "Queue" which would show the number of jobs waiting for that resource label.

#109 is somewhat related to this.
