### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by StephenB4431** [jenkinsci/lockable-resources-plugin#727]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  ```text
Jenkins v2.482
Lockable Resources 1322.v102a_16ce25ec
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10 Pro 22H1 (19045.4894)

### Reproduction steps

1. Go to Lockable Resources page when there is a queue.
2. Open the developer console

### Expected Results

No Errors

### Actual Results

Uncaught SyntaxError: Unexpected end of input

### Are you interested in contributing a fix?

The following event handler seems to be missing a closing brace & bracket:

```
  document.querySelectorAll(".lockable-resources-change-queue-order").forEach(function (button) {
    button.addEventListener("click", function (event) {
      changeQueueOrder(event.target.dataset.queueItemId);
    });
  }); <--- add this
```

**Comment by basil** [comment]
Sorry about that. This was fixed in #724.
