### ISSUE TITLE
Feature request : weights or other preference to matched resources

### ISSUE THREAD

**Issue by jimklimov** [jenkinsci/lockable-resources-plugin#81]
Currently AFAIK this plugin returns a random (or first?) one of the available resources matched by the requested label(s) or groovy script.

This feature request is to provide an ability to attach "preference weights" to returned values, so some resources are more likely to be locked for a particular request (e.g. customized groovy expression in a Jenkins job).

Use-case: we are testing builds of our product on a farm of devices with several tests - relatively fast basic testing, and then those versions which passed the basic tests are subjected to longer integration testing. Tests do take quite a while, so sometimes we have several built versions of the software ready to be tested - so several boxes at once can be utilized by a test (one for each new version).

While any device can run the basic test, just a subset of them can be used for integration tests because only they have the special connections (further HW appendages) needed for those test suites to succeed. Sometimes boxes are also grabbed and locked by developers to experiment their new features or support investigations on hardware, so they fall out from the CI-testing pool for that time.

Currently all these boxes are labeled (for this plugin) to use for basic tests, and that subset with appendages is also labeled for the specific tests. Effectively any of the unequal boxes can get occupied by a basic test, so if all special boxes are running the basic test, the special tests queue up and wait.

With this requested feature in place, the boxes without appendages would have a greater preference in the basic test job - so a queue of new builds would first use these boxes for the basic tests, and would only spill over to use available special boxes if there are many enough builds to be tested - more than the currently available pool of simpler devices. This way the special boxes are mostly available to pick up incoming integration testing jobs right away, but still can help with basic testing in bigger bursts of development.

Bonus points: if both a basic and an integration testing job are waiting in queue, and a "special" device becomes available, an integration job should have a way to be awarded with this device first. Maybe some magic with an even higher preference weight?..

**Comment by mPokornyETM** [comment]
See also #201
