### ISSUE TITLE
Lock blocks queue while node is free

### ISSUE THREAD

**Issue by rugosi** [jenkinsci/lockable-resources-plugin#88]
Hi,

Example for incorrect behavior
========================

Lockable_job_1 is running with LOCK_A on node 120.

Starting Lockable_job_2 with LOCK_A on node 110, but getting locked by LOCK_A, so it remains in the waiting queue, which is the correct behavior. 

Starting Lockable_job_3 with LOCK_B on node 110, but it gets locked by Lockable_job_B in the queue, while node 110 is free.

I think the plugin should not block the entire queue.

**Comment by rugosi** [comment]
JOB_OTHER is running on node 10.
OURJOB#1, needing lock LOCKJOB, is waiting for node 10 to achieve and block resource LOCKJOB.
OURJOB#2 is waiting in the queue for node 11, which is unused <-- blocked by OURJOB#1
OURJOB#3 is waiting in the queue for node 13, which is unused <-- blocked by OURJOB#2

**Comment by TobiX** [comment]
Yes, you can build deadlocks by unfortunate combinations between lockable resources and nodes where a job is able to run. This is not a bug. If you need finer control over your critical sections, use pipeline jobs.
