### ISSUE TITLE
No such property: resource for class: groovy.lang.Binding

### ISSUE THREAD

**Issue by jeff-deitch** [jenkinsci/lockable-resources-plugin#96]
For the last few months I've been using a build of https://github.com/jenkinsci/lockable-resources-plugin/pull/50 as I need to know the name of the resource that I am locking. I recently noticed that PR was closed in favor of https://github.com/jenkinsci/lockable-resources-plugin/pull/49, so I again went back to using the official build of the lockable resources plugin.

However, now I am getting the following error when a build tries to acquire a lock after having to wait due to all available resources being locked:
```
16:37:29 Trying to acquire lock on [Label: auto, Quantity: 1]
16:37:29 Found 0 available resource(s). Waiting for correct amount: 1.
16:37:29 [Label: auto, Quantity: 1] is locked, waiting...
16:39:06 Lock acquired on [Label: auto, Quantity: 1]
[Pipeline] {
[Pipeline] }
16:39:06 Lock released on resource [Label: auto, Quantity: 1]
[Pipeline] // lock
[Pipeline] echo
16:39:06 groovy.lang.MissingPropertyException: No such property: resource for class: groovy.lang.Binding
```
As long as there is a resource available when the lock is acquired, things work fine. It's just when we need to wait for a lock that we get this error.

It's also worth noting that https://github.com/jenkinsci/lockable-resources-plugin/pull/50 didn't suffer from this problem

**Comment by amuniz** [comment]
Can you file the issue in JIRA please?

**Comment by sheepdreamofandroids** [comment]
@jeff-deoyitch I created a fix in https://github.com/sheepdreamofandroids/lockable-resources-plugin . Could you check whether that fixes your problem? If it does, I can make it a pull request.

**Comment by jeff-deitch** [comment]
@sheepdreamofandroids I just built and installed your fix. I'll test it today and let you know if it looks good in a bit.

**Comment by jeff-deitch** [comment]
Sorry, looks like we're getting the error still:
```
09:55:18 Trying to acquire lock on [Label: auto, Quantity: 1]
09:55:18 Found 0 available resource(s). Waiting for correct amount: 1.
09:55:18 [Label: auto, Quantity: 1] is locked, waiting...
09:55:58 Lock acquired on [Label: auto, Quantity: 1]
09:55:58 Lock released on resource [Label: auto, Quantity: 1]
09:55:58 groovy.lang.MissingPropertyException: No such property: resource for class: groovy.lang.Binding
```
https://guides.github.com/features/mastering-markdown/

**Comment by sheepdreamofandroids** [comment]
While looking through commits that might have caused this, I found #95 which seems to fix this. I've tried to extend a unit test to check this but I can't run the tests for some reason. 

Anyway, it would probably be good to see whether that PR fixes the problem.

**Comment by jeff-deitch** [comment]
Looks like this has been fixed in the latest release. Thanks!
